# Generated by Django 6.1 on 2026-09-01 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_session_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('BUILDER_STARTED', 'Builder Started'), ('TIMETABLE_GENERATED', 'Timetable Generated'), ('PDF_GENERATED', 'PDF Generated')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['anonymous_session_id', 'event_type'], name='analytics_a_anonymo_f03e01_idx'), models.Index(fields=['timestamp', 'event_type'], name='analytics_a_timesta_628e96_idx')],
            },
        ),
    ]
